Repository ITE-Project1/pick-on-backend, pull requests merged in 2024-06, with the labels that each got.

#7 [상품] 지점별 상품 조회 (관리자)
  pom.xml
  src/main/java/com/ite/pickon/domain/product/controller/ProductController.java
  src/main/java/com/ite/pickon/domain/product/dto/ProductAdminVO.java
  src/main/java/com/ite/pickon/domain/product/dto/ProductVO.java
  src/main/java/com/ite/pickon/domain/product/mapper/ProductMapper.java
  src/main/java/com/ite/pickon/domain/product/service/ProductService.java
  src/main/java/com/ite/pickon/domain/product/service/ProductServiceImpl.java
  src/main/resources/com/ite/pickon/domain/order/mapper/OrderMapper.xml
  src/main/resources/com/ite/pickon/domain/product/mapper/ProductMapper.xml
  src/main/resources/com/ite/pickon/domain/stock/mapper/StockMapper.xml
  src/main/resources/com/ite/pickon/domain/transport/mapper/TransportMapper.xml
  src/main/resources/com/ite/pickon/domain/user/mapper/UserMapper.xml
  src/main/resources/com/ite/pickon/mapper/ProductMapper.xml
Labels: backend

#8 [운송] 상품 운송 배차 로직 구현
  src/main/java/com/ite/pickon/config/SchedulerConfig.java
  src/main/java/com/ite/pickon/domain/stock/dto/StockVO.java
  src/main/java/com/ite/pickon/domain/stock/mapper/StockMapper.java
  src/main/java/com/ite/pickon/domain/transport/TransportInformation.java
  src/main/java/com/ite/pickon/domain/transport/TransportSchedule.java
  src/main/java/com/ite/pickon/domain/transport/controller/TransportController.java
  src/main/java/com/ite/pickon/domain/transport/dto/TransportVO.java
  src/main/java/com/ite/pickon/domain/transport/mapper/TransportMapper.java
  src/main/java/com/ite/pickon/domain/transport/schedule/TransportScheduler.java
  src/main/java/com/ite/pickon/domain/transport/service/TransportService.java
  src/main/java/com/ite/pickon/domain/transport/service/TransportServiceImpl.java
  src/main/resources/com/ite/pickon/domain/stock/mapper/StockMapper.xml
  src/main/resources/com/ite/pickon/domain/transport/mapper/TransportMapper.xml
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
Labels: backend

#10 [주문] 목록 조회, 상세 조회, 예외핸들러
  pom.xml
  src/main/java/com/ite/pickon/domain/order/OrderStatus.java
  src/main/java/com/ite/pickon/domain/order/controller/OrderController.java
  src/main/java/com/ite/pickon/domain/order/dto/MultiOrderRes.java
  src/main/java/com/ite/pickon/domain/order/dto/OrderReq.java
  src/main/java/com/ite/pickon/domain/order/dto/OrderRes.java
  src/main/java/com/ite/pickon/domain/order/dto/OrderVO.java
  src/main/java/com/ite/pickon/domain/order/mapper/OrderMapper.java
  src/main/java/com/ite/pickon/domain/order/service/OrderService.java
  src/main/java/com/ite/pickon/domain/order/service/OrderServiceImpl.java
  src/main/java/com/ite/pickon/exception/CustomException.java
  src/main/java/com/ite/pickon/exception/ErrorCode.java
  src/main/java/com/ite/pickon/exception/ErrorResponse.java
  src/main/java/com/ite/pickon/exception/GlobalExceptionHandler.java
  src/main/java/com/ite/pickon/response/SimpleResponse.java
  src/main/resources/com/ite/pickon/domain/order/mapper/OrderMapper.xml
  src/main/resources/com/ite/pickon/domain/transport/mapper/TransportMapper.xml
  src/main/resources/com/ite/pickon/domain/user/mapper/UserMapper.xml
Labels: backend

#11 [운송] 배차 스케줄 및 정보 데이터 추가
  src/main/java/com/ite/pickon/domain/transport/TransportInformation.java
  src/main/java/com/ite/pickon/domain/transport/TransportSchedule.java
  src/main/java/com/ite/pickon/domain/transport/schedule/TransportScheduler.java
Labels: backend

#12 [상품] 상품등록, 상품 상세 조회 구현
  src/main/java/com/ite/pickon/domain/product/controller/ProductController.java
  src/main/java/com/ite/pickon/domain/product/dto/ProductRequest.java
  src/main/java/com/ite/pickon/domain/product/dto/ProductResponse.java
  src/main/java/com/ite/pickon/domain/product/dto/ProductVO.java
  src/main/java/com/ite/pickon/domain/product/mapper/ProductMapper.java
  src/main/java/com/ite/pickon/domain/product/service/ProductService.java
  src/main/java/com/ite/pickon/domain/product/service/ProductServiceImpl.java
  src/main/resources/com/ite/pickon/domain/order/mapper/OrderMapper.xml
  src/main/resources/com/ite/pickon/domain/product/mapper/ProductMapper.xml
  src/main/resources/com/ite/pickon/domain/transport/mapper/TransportMapper.xml
Labels: backend

#14 [상품] 관리자 지점별상품목록조회 url mapping 변경
  src/main/java/com/ite/pickon/domain/product/controller/ProductController.java
Labels: backend

#15 [주문] 주문하기
  src/main/java/com/ite/pickon/domain/order/controller/OrderController.java
  src/main/java/com/ite/pickon/domain/order/dto/OrderReq.java
  src/main/java/com/ite/pickon/domain/order/mapper/OrderMapper.java
  src/main/java/com/ite/pickon/domain/order/service/OrderService.java
  src/main/java/com/ite/pickon/domain/order/service/OrderServiceImpl.java
  src/main/java/com/ite/pickon/domain/stock/mapper/StockMapper.java
  src/main/java/com/ite/pickon/domain/stock/service/StockService.java
  src/main/java/com/ite/pickon/domain/stock/service/StockServiceImpl.java
  src/main/java/com/ite/pickon/domain/transport/dto/TransportVO.java
  src/main/java/com/ite/pickon/domain/transport/service/TransportServiceImpl.java
  src/main/java/com/ite/pickon/exception/ErrorCode.java
  src/main/java/com/ite/pickon/exception/GlobalExceptionHandler.java
  src/main/resources/com/ite/pickon/domain/order/mapper/OrderMapper.xml
  src/main/resources/com/ite/pickon/domain/stock/mapper/StockMapper.xml
Labels: backend

#16 [주문] 지점간 상품 배송 완료
  src/main/java/com/ite/pickon/domain/order/controller/OrderController.java
  src/main/java/com/ite/pickon/domain/order/dto/OrderReq.java
  src/main/java/com/ite/pickon/domain/order/mapper/OrderMapper.java
  src/main/java/com/ite/pickon/domain/order/service/OrderService.java
  src/main/java/com/ite/pickon/domain/order/service/OrderServiceImpl.java
  src/main/java/com/ite/pickon/domain/transport/TransportStatus.java
  src/main/java/com/ite/pickon/domain/transport/mapper/TransportMapper.java
  src/main/resources/com/ite/pickon/domain/order/mapper/OrderMapper.xml
  src/main/resources/com/ite/pickon/domain/transport/mapper/TransportMapper.xml
Labels: backend

#24 [상품] 관리자 지점별 상품 조회 쿼리 스트링 조건 변경
  src/main/java/com/ite/pickon/domain/product/controller/ProductController.java
Labels: backend

#25 [CORS] CORS 설정 - PATCH 추가
  src/main/webapp/WEB-INF/web.xml
Labels: backend

#32 [상품] 상품 등록 API 및 상품 코드 생성 로직 변경
  src/main/java/com/ite/pickon/domain/product/controller/ProductController.java
  src/main/java/com/ite/pickon/domain/product/dto/ProductRequest.java
  src/main/java/com/ite/pickon/domain/product/dto/ProductVO.java
  src/main/java/com/ite/pickon/domain/product/mapper/ProductMapper.java
  src/main/java/com/ite/pickon/domain/product/service/ProductService.java
  src/main/java/com/ite/pickon/domain/product/service/ProductServiceImpl.java
  src/main/resources/com/ite/pickon/domain/product/mapper/ProductMapper.xml
Labels: backend

#33 [주문] 주문조회 정렬 조건 변경, 바로 픽업 지점 재고 조정
  src/main/java/com/ite/pickon/domain/order/service/OrderServiceImpl.java
  src/main/resources/com/ite/pickon/domain/order/mapper/OrderMapper.xml
Labels: backend

#35 [유저] 관리자 유저 목록 조회 보완 및 상태 여러명 동시에 수정 가능하도록 변경
  src/main/java/com/ite/pickon/domain/product/service/ProductServiceImpl.java
  src/main/java/com/ite/pickon/domain/user/controller/UserController.java
  src/main/java/com/ite/pickon/domain/user/dto/UserAdminVO.java
  src/main/java/com/ite/pickon/domain/user/dto/UserVO.java
  src/main/java/com/ite/pickon/domain/user/mapper/UserMapper.java
  src/main/java/com/ite/pickon/domain/user/service/UserService.java
  src/main/java/com/ite/pickon/domain/user/service/UserServiceImpl.java
  src/main/resources/com/ite/pickon/domain/user/mapper/UserMapper.xml
Labels: backend

#42 [로깅] 콘솔 창에 로그 생성 안되는 이슈
  pom.xml
  src/main/resources/com/ite/pickon/domain/order/mapper/OrderMapper.xml
  src/main/resources/log4j2.xml
  src/main/resources/log4jdbc.log4j2.properties
Labels: backend, setting

#39 [상품] 관리자 상품 목록 조회 시 총 페이지 갯수도 담아서 응답
  src/main/java/com/ite/pickon/domain/product/controller/ProductController.java
  src/main/java/com/ite/pickon/domain/product/mapper/ProductMapper.java
  src/main/java/com/ite/pickon/domain/product/service/ProductService.java
  src/main/java/com/ite/pickon/domain/product/service/ProductServiceImpl.java
  src/main/java/com/ite/pickon/exception/ErrorCode.java
  src/main/java/com/ite/pickon/response/ListResponse.java
  src/main/resources/com/ite/pickon/domain/product/mapper/ProductMapper.xml
  src/main/resources/com/ite/pickon/domain/user/mapper/UserMapper.xml
Labels: backend

#43 [유저] 관리자 유저 목록 조회 페이징 로직 개선
  src/main/java/com/ite/pickon/domain/product/controller/ProductController.java
  src/main/java/com/ite/pickon/domain/user/controller/UserController.java
  src/main/java/com/ite/pickon/domain/user/mapper/UserMapper.java
  src/main/java/com/ite/pickon/domain/user/service/UserService.java
  src/main/java/com/ite/pickon/domain/user/service/UserServiceImpl.java
  src/main/java/com/ite/pickon/exception/ErrorCode.java
  src/main/resources/com/ite/pickon/domain/user/mapper/UserMapper.xml
Labels: backend

#45 [상품] 운송 상태 변경 스케줄링 mapper 쿼리 문법 오류 해결
  src/main/resources/com/ite/pickon/domain/transport/mapper/TransportMapper.xml
Labels: bug, backend

#53 [주문] 나의 주문 목록 조회 반환값 추가
  src/main/java/com/ite/pickon/domain/order/dto/MyOrderResponse.java
  src/main/java/com/ite/pickon/domain/order/service/OrderServiceImpl.java
  src/main/resources/com/ite/pickon/domain/order/mapper/OrderMapper.xml
Labels: backend

#58 [주문] 주문 날짜 반환 타입 수정, AOP 의존성 추가
  pom.xml
  src/main/java/com/ite/pickon/domain/order/dto/MyOrderResponse.java
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/spring/security-context.xml
  src/main/webapp/WEB-INF/web.xml
Labels: enhancement, backend

#61 [주문] 배송 완료 시 SMS 발송, 주문하기 Response 값 변경
  src/main/java/com/ite/pickon/domain/order/controller/OrderController.java
  src/main/java/com/ite/pickon/domain/order/dto/OrderRequest.java
  src/main/java/com/ite/pickon/domain/order/dto/OrderResponse.java
  src/main/java/com/ite/pickon/domain/order/mapper/OrderMapper.java
  src/main/java/com/ite/pickon/domain/order/service/OrderService.java
  src/main/java/com/ite/pickon/domain/order/service/OrderServiceImpl.java
  src/main/java/com/ite/pickon/domain/sms/template/SmsMessageTemplate.java
  src/main/resources/com/ite/pickon/domain/order/mapper/OrderMapper.xml
Labels: backend

#63 [타임존] UTC -> KST 변환
  src/main/java/com/ite/pickon/domain/order/dto/MyOrderResponse.java
  src/main/java/com/ite/pickon/domain/order/dto/OrderResponse.java
  src/main/java/com/ite/pickon/util/KSTDateSerializer.java
  src/main/resources/com/ite/pickon/domain/order/mapper/OrderMapper.xml
Labels: setting

#67 [환경변수] 환경 변수 설정
  .gitignore
  pom.xml
  src/main/java/com/ite/pickon/config/EnvConfig.java
  src/main/java/com/ite/pickon/domain/order/controller/OrderController.java
  src/main/java/com/ite/pickon/domain/sms/service/CoolSmsService.java
Labels: setting

#68 [주문] 재고 수량 조절 스토어드 프로시저로 처리, VO 통일, SMS 별도의 트랜잭션으로 분리
  src/main/java/com/ite/pickon/config/AsyncConfig.java
  src/main/java/com/ite/pickon/domain/order/controller/OrderController.java
  src/main/java/com/ite/pickon/domain/order/dto/MultiOrderResponse.java
  src/main/java/com/ite/pickon/domain/order/dto/OrderInfoVO.java
  src/main/java/com/ite/pickon/domain/order/dto/OrderRequest.java
  src/main/java/com/ite/pickon/domain/order/dto/OrderResponse.java
  src/main/java/com/ite/pickon/domain/order/dto/OrderVO.java
  src/main/java/com/ite/pickon/domain/order/mapper/OrderMapper.java
  src/main/java/com/ite/pickon/domain/order/service/OrderService.java
  src/main/java/com/ite/pickon/domain/order/service/OrderServiceImpl.java
  src/main/java/com/ite/pickon/domain/sms/event/SmsSendEvent.java
  src/main/java/com/ite/pickon/domain/sms/event/SmsSendEventListener.java
  src/main/java/com/ite/pickon/domain/sms/service/CoolSmsService.java
  src/main/java/com/ite/pickon/domain/stock/service/StockService.java
  src/main/java/com/ite/pickon/domain/stock/service/StockServiceImpl.java
  src/main/java/com/ite/pickon/exception/ErrorCode.java
  src/main/resources/com/ite/pickon/domain/order/mapper/OrderMapper.xml
  src/main/resources/com/ite/pickon/domain/stock/mapper/StockMapper.xml
Labels: backend

#71 [상품] DTO 정리
  .gitignore
  src/main/java/com/ite/pickon/HomeController.java
  src/main/java/com/ite/pickon/domain/order/service/OrderServiceImpl.java
  src/main/java/com/ite/pickon/domain/product/controller/ProductController.java
  src/main/java/com/ite/pickon/domain/product/dto/ProductInfoVO.java
  src/main/java/com/ite/pickon/domain/product/dto/ProductRequest.java
  src/main/java/com/ite/pickon/domain/product/dto/ProductVO.java
  src/main/java/com/ite/pickon/domain/product/mapper/ProductMapper.java
  src/main/java/com/ite/pickon/domain/product/service/ProductService.java
  src/main/java/com/ite/pickon/domain/product/service/ProductServiceImpl.java
  src/main/java/com/ite/pickon/domain/stock/controller/StockController.java
  src/main/java/com/ite/pickon/domain/stock/dto/StockRequest.java
  src/main/java/com/ite/pickon/domain/stock/dto/StockVO.java
  src/main/java/com/ite/pickon/domain/stock/mapper/StockMapper.java
  src/main/java/com/ite/pickon/domain/stock/service/StockService.java
  src/main/java/com/ite/pickon/domain/stock/service/StockServiceImpl.java
  src/main/resources/com/ite/pickon/domain/product/mapper/ProductMapper.xml
  src/main/resources/com/ite/pickon/domain/stock/mapper/StockMapper.xml
Labels: backend
